### ISSUE TITLE
Thoughts / Suggestions

### ISSUE THREAD

**Issue by xdaDaveShaw** [vivainio/TrivialBehinds#2]
Hi, I saw the request on twitter, and as an WinForms old hat (~10 in Production Code) I thought I'd take a look.

Not sure what format you were expecting the reply in, so I thought I'd write them in an issue here...

## Why the separate `Ui` wrapper type?

Could the same thing be achieved with an interface and a lot less writing of wrapper code, C# 6 makes light work of it

You could even recommend writing it as a nested interface inside the same file (or not depending on people coding standards ;))

So Form1 can look like this:

```csharp
public partial class Form1 :
    Form,
    Form1.IForm1Ui
{
    public Form1()
    {
        InitializeComponent();

        var d = TrivialBehinds.CreateBehind(
            this,
            this as IForm1Ui);

        Deactivate += (o, e) => d.Dispose();
    }

    Button IForm1Ui.Ok => _okButton;

    TextBox IForm1Ui.Content => _contentText;

    TextBox IForm1Ui.ResultText => _resultText;

    public interface IForm1Ui
    {
        Button Ok { get; }
        TextBox Content { get; }
        TextBox ResultText { get; }
    }
}
```

Looking at the code, this won't work perfectly without some changes to the implementation of TrivialBehinds, but I think it would be possible.

## Disposing

It should be possible to avoid the Behind returning an IDisposable that the Form needs to know about.
`IDisposable` should only be for Managed Resources.

By accessing the `Disposed` event handler in the `CreateBehind` (cast the passed in object as `Component`) and add on a handler to remove it from the internal collection.
If something isn't a Component, a method of `Remove` could be added to the returned type instead of `Dispose`

Deactivate doesn't work for non-modal dialogs as it is called when showing them.
e.g. Try a `form2.Show()`

## Summary

I don't think I will get a chance to use this much though - the end of WinForms is upon the application I work on (and I never got any F# into production code anyhow) - and I don't often create WinForms apps at home these days.

It does look useful though, and I don't mind keeping an eye on this where this goes and can chip in if needed.

**Comment by vivainio** [comment]
Thanks for the feedback!

On Ui wrapper type - 

Indeed the wrapper is not strictly necessary. There is a continuum on what you expose:

1. Full concrete wrapper type (as in current example)
2. Interface that exposes part of the Form (as you suggest). 
3. Exposing the concrete Form class itself

TrivialBehinds itself doesn't care, so I can address this by example/documentation. I'll see to it. 3) seems particularly attractive now that I think of it, you are only left with one line of boilerplate in .cs file if you have an utility function that creates the behind and registers disposer.

On disposing: CreateBehind can't take dependency on Windows.Forms (it's a netstandard2 library), so I can't bind that event handler there. But I can do it in an utility function. I'll see how this shapes up in code, should be good.

**Comment by vivainio** [comment]
Now I got this, as an implementation of  3):

```csharp
        public static void CreateComponentBehind<T>(T ctrl) where T : IComponent
        {
            var d = TrivialBehinds.CreateBehind<T>(ctrl, ctrl);
            ctrl.Disposed += (o, e) => d.Dispose();
        }
```

Instantiation sample here:

```csharp
namespace DesignerPart
{
    public partial class DirectForm : Form
    {
        public DirectForm()
        {
            InitializeComponent();
            TrivialBehinds.CreateComponentBehind(this);
        }
    }
}
```

I can use Disposed event because it's in System.ComponentModel.IComponent, which *is* part of netstandard2

**Comment by xdaDaveShaw** [comment]
That's a lot less friction for people to use.

As most Control's access modifiers are private, people can make public the ones they want people using in the F# Behind and keep the rest hidden.

One other thing I forgot yesterday,.. does it have to target netstandard 2.0?

_If_ I were to find an excuse to use this, I'd need a .NET Framework 4.0 version (sadly) - I could re-compile most of it as that if I needed to. I guess it depends on adoption.

**Comment by vivainio** [comment]
A very simple story could be:
- Use the netstandard2 library if that libary works on your end. 
- Copy-paste the single .cs file to somewhere in the project and use them in place.

**Comment by vivainio** [comment]
Closing as I believe the main issues were addressed by changes done (and the new release that's up). Thanks again for feedback and inspiration!
