### ISSUE TITLE
It works on User Controls?

### ISSUE THREAD

**Issue by Micha-kun** [vivainio/TrivialBehinds#3]
Hello, I'm unable to bind a user control with it's "behinder type". When I use it with the designer, it fails saying it cannot find the behinder type related to TrivialBehinds. Any recommenations? Thank you.

**Comment by vivainio** [comment]
Shouldn't be any problems. Did you try calling CreateComponentBehind in your form ctor, like so: 

https://github.com/vivainio/TrivialBehinds/blob/master/Sample/DesignerPart/DirectForm.cs

**Comment by Micha-kun** [comment]
Thank you for your quick answer. Yes, I tried to do that and doesn't fail on compile but when I try to use that user control on my form in design mode, it fails to insert it. Your sample only use Form instances, not UserControl instances. Could you try to upgrade your sample app using a UserControl for sharing what I could go wrong? Thank you.

**Comment by vivainio** [comment]
Yes, I can do that later today

**Comment by Micha-kun** [comment]
Thank you!

**Comment by Micha-kun** [comment]
Ups I closed by error XD

**Comment by vivainio** [comment]
This was crashing indeed. This is fixed in 1.2. Usage is as expected, added it to samples https://github.com/vivainio/TrivialBehinds/blob/master/Sample/DesignerPart/UserControl1.cs

**Comment by Micha-kun** [comment]
Thank you! This tool is getting better.
